var express = require('express');
var router = express.Router();

var User = require('../controlers/userscontroler');
var Images = require('../controlers/imagescontroler');
var confirm = require('../controlers/confirm');
var tagsList = require('../controlers/tagscontroler');
var getdata = require('../controlers/getdata');
var messages = require('../controlers/messagescontroler');
var notification = require('../controlers/notification');
var profile = require('../controlers/profilecontroler');
var visite = require('../controlers/visitehistorycontroler');
var jwt = require('../middleware/jwtMiddleware').jwtMidleware;
var block = require('../middleware/blockedUsers').blockMidllware;
router.post('/login', User.Login);
router.post('/signup', User.signup);
router.post('/confirm', confirm.confirm);
router.get('/users/:userId', User.read_a_user);
router.put('/users/:userId', jwt, User.update_a_user);
router.get('/tags', jwt, tagsList.list_all_tags);
router.get('/tags/:userId', jwt, tagsList.list_user_tags);
router.post('/tags', jwt, tagsList.create_a_tag);
router.get('/userdata/:username', jwt, getdata.userdata);
router.post('/images/:userId', jwt, Images.create_a_image);
router.post("/imagesdel/:userId", jwt, Images.deleteImage);
router.get("/images/:userId", jwt, Images.list_user_images);
router.get("/matches/:username", jwt, messages.matches);
router.get("/messages/:room", jwt, messages.getMessages);
router.get("/notification/:username", jwt, notification.getNotification);
router.post('/SetAllNotification', jwt, notification.setAllNotification);
router.post('/unliked/:username', jwt, block, profile.unliked);
router.post('/liked/:username', jwt, block, profile.liked);
router.post('/block/:username', jwt, profile.block);
router.post('/visite/',jwt, visite.addViste);
router.get('/visite/:username',jwt, visite.getVisitorsInfo);
// router.post('/unblock/:username', jwt, profile.unblock);
router.post('/report/:username', jwt, profile.report);
module.exports = router;