var express = require('express');
var router = express.Router();
var User = require('../controlers/userscontroler');
var Images = require('../controlers/imagescontroler');
var confirm = require('../controlers/confirm');
var tagsList = require('../controlers/tagscontroler');
var getdata = require('../controlers/getdata');
var messages = require('../controlers/messagescontroler');
var notification = require('../controlers/notification');
var profile = require('../controlers/profilecontroler');
var visite = require('../controlers/visitehistorycontroler');
var filter = require('../controlers/filtercontroler');
var checkProfil = require('../middleware/checkProfil').checkProfil;
var jwt = require('../middleware/jwtMiddleware').jwtMidleware;
var block = require('../middleware/blockedUsers').blockMidllware;
router.post('/login', User.Login);
router.post('/signup', User.signup);
router.post('/confirm', confirm.confirm);
router.post('/tags', jwt, tagsList.create_a_tag);
// router.post("/tagdel/:userId", jwt, tagsList.delete_a_tag);
router.post('/images', jwt, Images.create_a_image);
router.post('/imagesdel', jwt, Images.deleteImage);
router.post('/unliked/:username', jwt, block, checkProfil, profile.unliked);
router.post('/liked/:username', jwt, block, checkProfil, profile.liked);
router.post('/block/:username', jwt, profile.block);
router.post('/unblock/:username', jwt, profile.unblock);
router.post('/report/:username', jwt, profile.report);
router.post('/resetPasswd', User.reset);
router.post('/verifyRestPasswd', User.verifyRset);
router.post('/changepassword', User.changePassword);
router.post('/visite/', jwt, visite.addViste);
router.post('/SetAllNotification', jwt, notification.setAllNotification);
router.put('/users/', jwt, User.update_a_user);
router.put('/usersaccount/', jwt, User.update_account);
//router.get('/users/:userId', User.read_a_user);
router.get('/tags', jwt, tagsList.list_all_tags);
//router.get('/usertags/', jwt, tagsList.list_user_tags);
router.get('/userdata/:username', jwt, block, getdata.userdata);
//router.get("/images/:userId", jwt, Images.list_user_images);
router.get("/matches", jwt, messages.matches);
router.get("/messages/:room", jwt, messages.getMessages);
router.get("/notification", jwt, notification.getNotification);
router.get('/newNotification', jwt, notification.newNotification);
router.get('/visite/', jwt, visite.getVisitorsInfo);
router.get('/filteredUsers/', jwt, filter.usersFiltred);
router.get('/matchedUsers/', jwt, filter.usersMatched);
router.get('/suggestedUsers/', jwt, filter.usersSuggested);
router.get('/likedUsers/', jwt, filter.usersLiked);
router.get('/userslikesyou/', jwt, filter.usersLikedYou);
router.get('/blocked', jwt, profile.blockedUsers);
module.exports = router;